language: csharp
solution: ".NET Portable TypeCast.sln"
install:
  - nuget restore ".NET Portable TypeCast.sln"
  - nuget install nunit.consolerunner -Version 3.4.1 -OutputDirectory packages
script:
  - mono --version
  - xbuild /p:Configuration=Release ".NET Portable TypeCast.sln"
  - mono ./packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe --full --workers=1 ./TypeCast.Tests/bin/Release/Tests.dll
mono:
  - latest
  - 4.4.2
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: latest
    - os: osx
      osx_image: xcode7.2
      mono: latest
  allow_failures:
    - os: osx
  fast_finish: true
  