version: 3.1.0.{build}-beta 

platform:
  - x64
  - Any CPU

configuration:
  - Release
  #- Debug

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

matrix:
  fast_finish: true

  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Debug

# branches to build
branches: 
  only: 
    - master 
    - production
    - experimental

  except:
    - gh-pages


image: Visual Studio 2015 

assembly_info: 
  patch: true 
  file: '**\AssemblyInfo.*' 
  assembly_version: '{version}' 
  assembly_file_version: '{version}' 
  assembly_informational_version: '{version}' 

install: 
- cmd: 

nuget: 
  account_feed: true 
  project_feed: true 
  disable_publish_on_pr: true 

before_package:
  - cmd: echo "Packaging now!"
  
  
before_build: 
  - cmd:  git checkout experimental
  #- cmd: git fetch origin master:master
  #- cmd: git pull
  - cmd: git log --graph --all --color --date=relative --pretty=format:"%Cred%x09%h %Creset%ad%Cgreen%d %Creset %s %C(bold)(%an)%Creset"
  - cmd: nuget restore ".NET Portable TypeCast.sln"

build: 
  parallel: true
  project: ".NET Portable TypeCast.sln"
  publish_nuget: true 
  publish_nuget_symbols: true 
  include_nuget_references: true 
  verbosity: detailed 

after_build:
  - cmd: copy README.md %APPVEYOR_BUILD_FOLDER%\TypeCast\bin\README.md
  - cmd: git log --graph --all --date=relative --pretty=format:"%x09 %ad %d %s (%aN)" > CHANGELOG
  - cmd: >- 
          7z a DotNetCastConvertTransform.zip %APPVEYOR_BUILD_FOLDER%\TypeCast\bin\*.*
          appveyor PushArtifact DotNetCastConvertTransform.zip 

after_test:
  - ps:   .\NuGet\pack.ps1 "TypeCast" "Core.TypeCast" "Core.Cast-Transform-Convert"
  
deploy: 
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: false       # deploy on tag push only

  # Deploying to NuGet feed
  - provider: NuGet
    #server: https://my.nuget.server/feed
    api_key:
      secure: jGbn/mXu3fLPmAuMgXcRMVAY7GAt3d5AKn5Aa+6ac5sNZdoW64RHv3LeUK1nz/Zg
    skip_symbols: false
    #symbol_server: https://your.symbol.server/feed
    artifact: /.*\.nupkg/
    
notifications: 
  - provider: Email 
    to: 
    - lorenz.lo.sauer@gmail.com
    on_build_success: false 
    on_build_failure: true 
    on_build_status_changed: false

  - provider: Webhook
    url: https://webhooks.gitter.im/e/23956b01699c1e6d3f8f
    method: GET

  - provider: GitHubPullRequest
    auth_token:
      secure: JEasSfnCSjLkQbLg5yWenG/o1oAS5GSUWfOzEu4YswsNb/zFRRaex7CfLbMQbEUh
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
    
skip_commits:
  # Regex for matching commit message
  message: /Update.*\.(md)/

  files:
    - bin/Release/**/*
    - bin/Debug/**/*

only_commits:
  files:
    - Examples/*
    - '**/*.cs'
    - '**/*.csproj'
    - '**/*.config'
    - '**/*.sln'
    - appveyor.yml