version: 3.1.0.{build}-beta 

platform:
  - x64
  - Any CPU

configuration:
  - Release
  #- Debug

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

matrix:
  fast_finish: true

  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Debug

# branches to build
branches: 
  only: 
    - master 
    - production
    - experimental

  except:
    - gh-pages


image: Visual Studio 2015 

assembly_info: 
  patch: true 
  file: '**\AssemblyInfo.*' 
  assembly_version: '{version}' 
  assembly_file_version: '{version}' 
  assembly_informational_version: '{version}' 


environment:
  access_token:
    secure: hDtElcG5tKay8VLXhoC7Y5AVHZtLoEpXc0bc2lVCHwkoQYwe+dgO+pecWheMlZsa

install: 
  - cmd: echo "Install started..."
  - cmd:  git checkout experimental

nuget: 
  account_feed: true 
  project_feed: true 
  disable_publish_on_pr: true 

before_package:
  - cmd: echo "Packaging now!"
  
before_build: 
  - cmd: echo "Before Build Environmental variables..."
  - ps: 'ls env:'
  #- cmd: git fetch origin master:master
  #- cmd: git pull
  - cmd: 'git log --graph --all --date=relative'
  - cmd: nuget restore ".NET Portable TypeCast.sln"

build: 
  parallel: true
  project: ".NET Portable TypeCast.sln"
  publish_nuget: true 
  publish_nuget_symbols: true 
  include_nuget_references: true 
  verbosity: normal 

after_build:
  - cmd: echo "After Build Environmental variables..."
  - ps: 'ls env:'

after_test:
  - bash <(curl -s https://codecov.io/bash)

artifacts: 
  - path: deploy\*.zip
    name: TypeCastRelease
    
after_test:
  - cmd: copy README.md %APPVEYOR_BUILD_FOLDER%\TypeCast\bin\README.md
  - cmd: 'git log --graph --all --date=relative > .\CHANGELOG.txt'
  - cmd: copy .\CHANGELOG.txt %APPVEYOR_BUILD_FOLDER%\TypeCast\bin\CHANGELOG.txt
  - cmd: copy TypeCast\bin\x64\Release\*.* %APPVEYOR_BUILD_FOLDER%\TypeCast\bin\
  - ps:  '.\NuGet\pack.ps1 "TypeCast" "Core.TypeCast" "Core.Cast-Transform-Convert"'
  - cmd: copy .\*.nupkg %APPVEYOR_BUILD_FOLDER%\TypeCast\bin\
  - cmd: mkdir deploy
  - cmd: 7z a deploy\DotNetCastConvertTransform.zip %APPVEYOR_BUILD_FOLDER%\TypeCast\bin\*.*
  - cmd: appveyor PushArtifact deploy\DotNetCastConvertTransform.zip 
  
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "lorenz.lo.sauer@gmail.com"
  - git config --global user.name "Lo Sauer"
  - git tag "{version}"
  - git push origin --tags
  
deploy: 
  # Deploy to GitHub Releases
  - provider: GitHub
    #release: TypeCast-v$(APPVEYOR_BUILD_VERSION)
    description: 'TypeCast uncompromising Conversions'
    auth_token:
      secure: hDtElcG5tKay8VLXhoC7Y5AVHZtLoEpXc0bc2lVCHwkoQYwe+dgO+pecWheMlZsa
    artifact: TypeCastRelease            # upload artifact package to release assets
    draft: false
    prerelease: false
    on:
      branch: experimental           # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only

  # Deploying to NuGet feed
  - provider: NuGet
    #server: https://my.nuget.server/feed
    api_key:
      secure: jGbn/mXu3fLPmAuMgXcRMVAY7GAt3d5AKn5Aa+6ac5sNZdoW64RHv3LeUK1nz/Zg
    skip_symbols: false
    #symbol_server: https://your.symbol.server/feed
    artifact: "Core.Cast-Transform-Convert.{version}.nupkg"
    
notifications: 
  - provider: Email 
    to: 
    - lorenz.lo.sauer@gmail.com
    on_build_success: false 
    on_build_failure: true 
    on_build_status_changed: false

  - provider: Webhook
    url: https://webhooks.gitter.im/e/23956b01699c1e6d3f8f
    method: GET

  - provider: GitHubPullRequest
    auth_token:
      secure: JEasSfnCSjLkQbLg5yWenG/o1oAS5GSUWfOzEu4YswsNb/zFRRaex7CfLbMQbEUh
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"
    
skip_commits:
  # Regex for matching commit message
  message: /Update.*\.(md)/

  files:
    - bin/Release/**/*
    - bin/Debug/**/*

only_commits:
  files:
    - Examples/*
    - '**/*.cs'
    - '**/*.csproj'
    - '**/*.config'
    - '**/*.sln'
    - appveyor.yml